Repository MIT-Emerging-Talent/ET6-CDSP-group-18-repo, pull requests merged in 2025-06, with the labels that each got.

#5 Merge: team availability and communication setup
  collaboration/communication.md
Labels: communication

#12 Update constraints.md
  collaboration/constraints.md
Labels: documentation, communication, team-review

#20 Retrospective milestone 0
  collaboration/retrospectives/0_cross_cultural_collaboration.md
Labels: communication

#26 Add: content to CONTRIBUTING.md
  .ls-lint.yml
  CONTRIBUTING.md
  requirements.txt
Labels: documentation, communication
